solr:
  host: localhost
  port: 8983

db:
  host: localhost
  port: 5433
  name: archiveservice
  username: postgres
  password: 123
  
server:
  port: 9090
  
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}?stringtype=unspecified
    username: ${db.username}
    password: ${db.password}
  jpa:
    show-sql: true
    hibernate:
        ddl-auto: create
    properties:
        hibernate:
            dialect: org.hibernate.dialect.PostgreSQL95Dialect

jks:
  path: C:\CIRB-Projects\ProjectArchiving\key
  password: P@ssw0rd

encryption:
  key: cirbAESkey
